"""Added more data to the model

Revision ID: 2a62bd4de518
Revises: 77ff80088a03
Create Date: 2025-05-23 13:28:29.233617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a62bd4de518'
down_revision: Union[str, None] = '77ff80088a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('feels_like', sa.Float(), nullable=False))
    op.add_column('weather', sa.Column('temp_min', sa.Float(), nullable=False))
    op.add_column('weather', sa.Column('temp_max', sa.Float(), nullable=False))
    op.add_column('weather', sa.Column('pressure', sa.Integer(), nullable=False))
    op.add_column('weather', sa.Column('humidity', sa.Integer(), nullable=False))
    op.add_column('weather', sa.Column('wind_speed', sa.Float(), nullable=False))
    op.add_column('weather', sa.Column('wind_deg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'wind_deg')
    op.drop_column('weather', 'wind_speed')
    op.drop_column('weather', 'humidity')
    op.drop_column('weather', 'pressure')
    op.drop_column('weather', 'temp_max')
    op.drop_column('weather', 'temp_min')
    op.drop_column('weather', 'feels_like')
    # ### end Alembic commands ###
